### ISSUE TITLE
Any progress on UCM/pavucontrol?

### ISSUE THREAD

**Issue by mryndzionek** [EMLommers/Apollolake_Audio#6]
First of all thanks for this repo! I have a x360 11 G1 EE and finally have some sound. I'm wondering what is needed to get headphones, the volume scaling and mic going? `Aplay -l` looks promising (lists speakers and **headset**), but under pavucontrol there are only 'Headphones', which are actually speakers. Any idea on how to proceed to get to the bottom of it?

**Comment by EMLommers** [comment]
I am working on the original use of the bin/tplg file from Google, to  get it working on cuurent machines.
The reason is I cannot change, or is absent  the alsa widget media* and codec*
My assumption this is a SOF issue. 
As soon as some vars are adjustable  and can control the media_in/out and codec0_in/out and codec1_in.out it is possible., it is related to the pin number of the Dialog 7219 and MAX98357A.

**Comment by mryndzionek** [comment]
Okay, understood. I'll be monitoring SOF. Also, let me know if something needs testing. Thanks again!

**Comment by EMLommers** [comment]
Hi, awaiting on SOF issue:
https://github.com/thesofproject/sof/issues/6249
